### ISSUE TITLE
[Bug]: theme issue

### ISSUE THREAD

**Issue by awaiskhan0** [morethanmin/morethan-log#162]
### Describe the bug

In `site.config.js`, changing 

```
theme: "light", // ['light', 'dark', 'auto']
```
to
```
theme: ['light', 'dark', 'auto'],
```
causes the following error:
```
./src/components/Layout/Header/ThemeToggle.tsx:26:7
--
07:31:26.924 | Type error: This comparison appears to be unintentional because the types 'string[]' and 'string' have no overlap.
Expand 7 Lines
07:31:26.954 | error Command failed with exit code 1.
07:31:26.954 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
07:31:26.973 | Error: Command "yarn run build" exited with 1
07:31:27.810 | Deployment completed
07:31:27.416 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

### To reproduce

1. Go to `site.config.js`
2. Change `theme` value from `"light",` to `['light', 'dark', 'auto']`
3. Deploy on vercer

### Browser

Google Chrome Version 111.0.5563.149 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by morethanmin** [comment]
Choose one out of three and enter it!
