### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by seanpan704** [morethanmin/morethan-log#266]
### Describe the bug

Vercel deployment failed.

I keep running into this issue when deploying on Vercel.

<html>
<body>

Failed to compile.
--
15:10:58.188 |  
15:10:58.188 | ./src/routes/Detail/PostDetail/CommentBox/Utterances.tsx:28:11
15:10:58.188 | Type error: Type '{ repo: string \| undefined; "issue-term": string; label: string; }' is not assignable to type '{ [key: string]: string; }'.
15:10:58.188 | Property 'repo' is incompatible with index signature.
15:10:58.189 | Type 'string \| undefined' is not assignable to type 'string'.
15:10:58.189 | Type 'undefined' is not assignable to type 'string'.
15:10:58.189 |  
15:10:58.189 | 26 \|     script.setAttribute("issue-term", issueTerm)
15:10:58.189 | 27 \|     script.setAttribute("theme", theme)
15:10:58.189 | > 28 \|     const config: { [key: string]: string } = CONFIG.utterances.config
15:10:58.189 | \|           ^
15:10:58.189 | 29 \|     Object.keys(config).forEach((key) => {
15:10:58.189 | 30 \|       script.setAttribute(key, config[key])
15:10:58.190 | 31 \|     })
15:10:58.298 | error Command failed with exit code 1.

</body>
</html>

Sorry I'm new to this, any help is appreciated!

Thank you!

### To reproduce

See error

### Browser

Microsoft Edge v116, Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by SeongIkKim** [comment]
`Utterances` are comment system by github issues.
You need to modify utterances enable to False in `site.config.js` before deploying. You can check image below which was in guideline in readme.
![image](https://github.com/morethanmin/morethan-log/assets/26772420/0d8edc23-ea5e-40a7-a9cc-5d94f65c16f0)

- When you fork a repository like this, you can't find Issues tap like you create your own repository. Utterances use issues tap, so you have to do a few manual steps more to build your own comment system.
- After deploying your blog in vercel, you should modify utterances configurations in `site.config.js` like [this(It's my blog config)](https://github.com/SeongIkKim/morethan-log/blob/main/site.config.js). Enable utterances, create a new repo for comments and replace utterances repo name in `site.config.js` with this.
  - [Related issue comment](https://github.com/morethanmin/morethan-log/issues/116#issuecomment-1439313113)
