### ISSUE TITLE
[Bug]: I'm getting errors and warnings when deploying to vercel (Building)

### ISSUE THREAD

**Issue by johnmol** [morethanmin/morethan-log#267]
### Describe the bug

<html>
<body>

I'm getting the following errors when deploying to vercel (Building)

## **Warning 1**
./src/hooks/useScheme.ts
--
21:14:04.746 | 31:6  Warning: React Hook useEffect has a missing dependency: 'setScheme'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
## **Warning 2**
21:14:04.746 |  
21:14:04.747 | ./src/routes/Detail/PostDetail/CommentBox/Utterances.tsx
21:14:04.747 | 36:6  Warning: React Hook useEffect has a missing dependency: 'issueTerm'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
## **Warning 3**
21:14:04.747 |  
21:14:04.747 | ./src/routes/Feed/PostList/index.tsx
21:14:04.747 | 51:6  Warning: React Hook useEffect has a missing dependency: 'data'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
21:14:04.747 |  
21:14:04.747 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
## **Error**
21:14:06.495 | Failed to compile.
21:14:06.495 |  
21:14:06.496 | ./src/routes/Detail/PostDetail/CommentBox/Utterances.tsx:28:11
21:14:06.496 | Type error: Type '{ repo: string \| undefined; "issue-term": string; label: string; }' is not assignable to type '{ [key: string]: string; }'.
21:14:06.496 | Property 'repo' is incompatible with index signature.
21:14:06.496 | Type 'string \| undefined' is not assignable to type 'string'.
21:14:06.496 | Type 'undefined' is not assignable to type 'string'.
21:14:06.496 |  
21:14:06.496 | 26 \|     script.setAttribute("issue-term", issueTerm)
21:14:06.496 | 27 \|     script.setAttribute("theme", theme)
21:14:06.496 | > 28 \|     const config: { [key: string]: string } = CONFIG.utterances.config
21:14:06.498 | \|           ^
21:14:06.498 | 29 \|     Object.keys(config).forEach((key) => {
21:14:06.498 | 30 \|       script.setAttribute(key, config[key])
21:14:06.498 | 31 \|     })
21:14:06.537 | error Command failed with exit code 1.
21:14:06.537 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:14:06.568 | Error: Command "yarn run build" exited with 1

</body>
</html>

### To reproduce

Forked the repo
Followed step 6: Deploy on Vercel, with the following environment variables.

### Browser

Google Chrome, Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by seanpan704** [comment]
I have the same issue.

**Comment by SeongIkKim** [comment]
Check [this comment](https://github.com/morethanmin/morethan-log/issues/266#issuecomment-1685192619)

**Comment by realrlgus** [comment]
![스크린샷 2023-08-20 오후 10 23 10](https://github.com/morethanmin/morethan-log/assets/28673540/9eb45ba3-52e7-4782-b264-8bb9fd1097d7)
change repo : process.env.NEXT_PUBLIC_UTTERANCES_REPO 
to 
process.env.NEXT_PUBLIC_UTTERANCES_REPO || ""

**Comment by haideriqbal** [comment]
You can also hardcode the `repo` value to your repo in utterances to fix the build which is currently broken on master. It solved issue for me. `repo: process.env.NEXT_PUBLIC_UTTERANCES_REPO` -> `repo: {your_repo}`.

Check this [commit](https://github.com/morethanmin/morethan-log/commit/47d536ceebfd81cd068002209308dfdb0fad6d2d).

**Comment by johnmol** [comment]
Thank you for everyone's help. @haideriqbal solution worked well for me.

[Commit](https://github.com/morethanmin/morethan-log/commit/47d536ceebfd81cd068002209308dfdb0fad6d2d).
