### ISSUE TITLE
[Bug]: Mobile Night Mode icon not displayed

### ISSUE THREAD

**Issue by 712346867** [morethanmin/morethan-log#297]
### Describe the bug

The upper right corner of the screen clicked, but the icon did not show up

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Browser

ios

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by singsongmay** [comment]
저도 같은 문제를 겪고 있습니다. Safari에서 나이트모드, Tag/Search/Profile 이모지가 뜨지 않습니다. Chrome에서는 뜹니다. Morethan-log 예시 블로그에서도 뜨지 않는 것을 확인하였습니다.

**Comment by PurpleSand123** [comment]
[noto-emoji](https://github.com/googlefonts/noto-emoji?tab=readme-ov-file#using-notocoloremoji) Emoji의 폰트가 Noto Color Emoji로 되어있고, "On macOS, only Chrome supports it" 라고 적혀있네요.
이 부분을 해결하려면 폰트를 바꾸는 작업을 진행해야할 것 같습니다.

**Comment by 712346867** [comment]
What I am referring to is that the switching icon between night mode and day mode is not displayed, not the emoji. This bug has not been fixed yet.

**Comment by PurpleSand123** [comment]
What do you mean "icon between night mode and day mode"? Please give us a screenshot of your problem. I think switching icon is emoji component.
