### ISSUE TITLE
[Bug]: Unavailable Dynamic Sitemap

### ISSUE THREAD

**Issue by yureutaejin** [morethanmin/morethan-log#336]
### Describe the bug

안녕하세요. 블로그 잘 사용하던 중에 궁금한 게 있어 이슈 남깁니다.

현재 next site config를 사용해서 배포할 때는 정적으로 sitemap을 생성하는 것을 확인했습니다.
하지만 노션 페이지 추가에 따라 동적으로 sitemap이 변경되지 않는 것 같습니다.
이전 #19 에서 설명하신 /page/sitemap.xml.js가 현재는 main 브랜치에 보이지 않더군요. 포스팅보고 임의로 추가해서 진행도 해보고, 다른 next js 포스팅들 보고도 해봤는데 생성되지 않아서 남깁니다.
제가 아는 동적 sitemap 생성과 의미가 다른건가요? ( notion page 추가 시, 각 페이지 slug 생성에 따라 sitemap에도 추가 생성)
next js에 대해 문외한이라 죄송합니다.

### To reproduce

1. Go to /page folder and create /page/sitemap.xml.js
2. Make a code according to #19 
3. Push branch and Deploy to Vercel

### Browser

mac OS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by pg56714** [comment]
fix done

**Comment by yureutaejin** [comment]
@pg56714

OMG...Thanks for your contribution ^^
I will try it on my fork
