### ISSUE TITLE
[Bug]: Post are not auto updating

### ISSUE THREAD

**Issue by TyrrellDMB** [morethanmin/morethan-log#342]
### Describe the bug

When I publish a new page they do not update.

### To reproduce

My post don't auto update

### Browser

Edge & Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Ishannaik** [comment]
Having the same issue have to redeploy to update the posts.

**Comment by phuocvj** [comment]
+1 Same issue

**Comment by TyrrellDMB** [comment]
The solution to this issue is set revalidateTime to 1. It's in the site.config file.

revalidateTime: 1
