### ISSUE TITLE
[Bug]: Profile picture not showing correctly

### ISSUE THREAD

**Issue by lucas-tavano** [morethanmin/morethan-log#354]
### Describe the bug

When i put myself as an author, appears like this:
![image](https://github.com/morethanmin/morethan-log/assets/164281809/e978b914-5f24-4919-a7f6-d845d2ca25e0)

Reviewed my Notion account and i dont think its some account configuration...
Tried to troubleshoot but i couldn't. 

### To reproduce

1. Go to https://lucas-tavano.vercel.app/test
2. Look on author
3. See error.

### Browser

W10 - Chrome Version 123.0.6312.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by lucas-tavano** [comment]
Nevermind, it was really the Notion, excluded my photo and uploaded again and then it worked. 
thanks!

**Comment by topeogunleye** [comment]
> Nevermind, it was really the Notion, excluded my photo and uploaded again and then it worked. thanks!

Hi @lucas-tavano, I'm having this same issue please. How did you fix it using Notion?

**Comment by topeogunleye** [comment]
Solution, I reuploaded my image on Notion.
