### ISSUE TITLE
다크모드 해제 설정 방법

### ISSUE THREAD

**Issue by dav1n9** [morethanmin/morethan-log#370]
### Describe the bug

다크모드가 기본으로 설정되어 있는 것 같은데, 기본적으로 다크 모드를 비활성화 하려면 어떻게 해야하나요?

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Browser

chrome

### Validations

- [x] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by pg56714** [comment]
@dav1n9
go to site.config.js
see
blog: {
    title: "morethan-log",
    description: "welcome to morethan-log!",
    scheme: "dark", // 'light' | 'dark' | 'system'.     <----- here
  },
