### ISSUE TITLE
Request for Self-Hosting Tutorial

### ISSUE THREAD

**Issue by Fauzanmhr** [morethanmin/morethan-log#376]
Hello Maintainers,

First off, thank you for creating and maintaining this awesome project! It has been incredibly useful for me in making my blog easily.

I understand that Vercel provides a seamless deployment experience, which is fantastic for many users. However, I believe that having a self-hosting option would greatly benefit those who prefer or need to deploy on their own servers.

**Comment by Fauzanmhr** [comment]
For now, it works well with DokPloy Panel and uses Build Type: Heroku Buildpacks

**Comment by yishuiwang** [comment]
I think you can check this docs: https://github.com/morethanmin/morethan-log/blob/main/.github/CONTRIBUTING.md

**Comment by Fauzanmhr** [comment]
Ah thank you
