### ISSUE TITLE
Deployment with Docker

### ISSUE THREAD

**Issue by nickelswitte** [morethanmin/morethan-log#48]
## **Overview**
Introducing the possibility to deploy this via docker

I really like the project, but I would like to self-host it with docker. Is that a possibility?

**Comment by morethanmin** [comment]
Thanks for the issue, But very unfortunately docker is not yet considered on my roadmap. I will work on it if more users request it.

I'd be very grateful if you worked on Deployment with Docker.

**Comment by nickelswitte** [comment]
Ah, that is sad! Sorry, I do not have the capabilities, to do this right now.
