### ISSUE TITLE
노션 반영이 안됩니다

### ISSUE THREAD

**Issue by inmoG** [morethanmin/morethan-log#52]
## **Overview**
샘플 글을 지우고 아래와 같이 제 글을 작성 후 배포 하였으나 2번째 그림처럼 글이 출력되지 않아요 해결 방법을 모르겠습니다.
![image](https://user-images.githubusercontent.com/50260620/210412789-36f031bc-583e-4f6a-a815-1b8c60afafe7.png)

![image](https://user-images.githubusercontent.com/50260620/210412738-0b56c48d-5f01-400c-a418-f385d47f5f53.png)

**Comment by morethanmin** [comment]
NOTION_PAGE_ID 에 값이 잘 입력되어있을까요? 입력되어있다면 어떠한 값이 입력되어있나요?

글을 지우기 전에는 샘플 글이 표시되었나요? 

https://blog-inmog.vercel.app

요기 배포된걸 보니... 잘보이는 것 같기도 한데.. 혹시 해결이 되셨나요!?

**Comment by inmoG** [comment]
흠 어제 제가 들어간 도메인이 잘못됬나봐요 살짝 느리지만 반영 잘 되네요! ㅎㅎ 좋은 서비스 만들어주셔서 감사합니다 :)

**Comment by morethanmin** [comment]
혹시 또 문제가 발생하면 이슈남겨주세요~ 감사합니다 :-)

**Comment by inmoG** [comment]
https://morethan-log-one.vercel.app/%ED%85%8C%EC%8A%A4%ED%8A%B8

제 노션에 반영되는 author와 블로그에 반영되는 author가 다릅니다. author 업데이트가 안되네요 ㅠㅠ
