### ISSUE TITLE
Asc 를 기본 설정으로 지정하는 방법이 궁금합니다!

### ISSUE THREAD

**Issue by inmoG** [morethanmin/morethan-log#55]
## **Overview**
안녕하세요 블로그 접속할 때 마다 DESC로 지정되는게 불편해서 정렬 기본값을 Asc로 바꾸고 싶은데 어떻게 변경할 수 있나요?

**Comment by morethanmin** [comment]
코드 상에 `currentOrder` 라는 이름의 상수가 있습니다. 해당 값의 기본 값을 수정해주시면 됩니다.

여러곳에서 정의하고 있다면 모두 동일하게 바꿔주시면 됩니다.

감사합니다!
