### ISSUE TITLE
Author 반영이 안됩니다

### ISSUE THREAD

**Issue by inmoG** [morethanmin/morethan-log#57]
## **Overview**

https://blog-inmog.vercel.app/author

제 노션에 반영되는 author와 블로그에 반영되는 author가 다릅니다. author 업데이트가 안되네요 ㅠㅠ

**Comment by morethanmin** [comment]
안녕하세요! 해당 링크가 확인이 안되네요. 아직 문제 발생하신다면 다시 공유 부탁드리겠습니다!

**Comment by inmoG** [comment]
https://inmo-log.vercel.app/Path%20traversal 링크입니다 
아직 동일 증상 발생합니다

**Comment by morethanmin** [comment]
해당 이슈 수정하여 배포되었습니다 :) 문제없다면 해당 이슈를 close 해주세요! (#63)

**Comment by inmoG** [comment]
이름은 잘 출력 되는데 프로필 이미지가 뜨지 않습니다!
![image](https://user-images.githubusercontent.com/50260620/212399384-3bf6aae2-9ed6-44cd-bb87-729d85206dfb.png)

**Comment by morethanmin** [comment]
해당 이슈 수정해서 머지했습니다.  #71 
fork되어있는 repo에서 update 해주시면 해결 될 것 같습니다 ㅎㅎ

**Comment by inmoG** [comment]
감사합니다! 블로그 너무 마음에 들어요 ㅎㅎ
