### ISSUE TITLE
노션에 author 이미지파일이 없을 경우 직렬화 에러

### ISSUE THREAD

**Issue by Stralighteel** [morethanmin/morethan-log#61]
## **Overview**
노션 게시물을 제꺼로 변경하는 와중에 자꾸 에러가 떠서 원인을 찾아보니 직렬화 에러가 뭐시기.. 하더라고요. 
노션 게시글의 author의 이미지를 참조할 수 없으면 렌더 과정에서 문제가 생기는 것 같습니다. 

undefined 때문에 넘어가지질 않아서 아래 내용으로 코드를 고쳐서 이슈해결했습니다. 
`profile_photo: resValue?.profile_photo ?? null`

**Comment by morethanmin** [comment]
안녕하세요! 이슈 남겨주셔서 너무 감사합니다 ㅎㅎ 해당 부분은 업데이트에 반영하겠습니다!
