### ISSUE TITLE
토글안에 있는 링크

### ISSUE THREAD

**Issue by yoosion030** [morethanmin/morethan-log#62]
## **Overview**
일반 링크는 잘 보이지만
<img width="1094" alt="스크린샷 2023-01-11 오후 7 10 34" src="https://user-images.githubusercontent.com/80191860/211778292-daa86c64-0ffb-4543-8d4d-a3a0417253cf.png">

아래와 같이 토글안에 있는 링크는
<img width="1128" alt="스크린샷 2023-01-11 오후 7 08 11" src="https://user-images.githubusercontent.com/80191860/211778107-a2f2e0b7-7536-47eb-821a-8b27ba49170e.png">

페이지 밖을 벗어나버립니다.

**Comment by morethanmin** [comment]
안녕하세요! 이슈 감사드립니다. 한번 확인해볼게요!

**Comment by morethanmin** [comment]
혹시 해당 이슈가 발생하는 페이지 공유가 가능할까요? 테스트 해보고있는데 정확히 어떤 경우인지 파악이 어렵네요 🥲

**Comment by yoosion030** [comment]
> 혹시 해당 이슈가 발생하는 페이지 공유가 가능할까요? 테스트 해보고있는데 정확히 어떤 경우인지 파악이 어렵네요 🥲

https://sion-log.vercel.app/2022-sw-meister-hackathon
**유용한 사이트** 
토글에서 이 에러가 발생합니다 ㅜㅜ

**Comment by JaeSang1998** [comment]
[https://github.com/morethanmin/morethan-log/pull/68](url)

이 태그 추가해서 간단하게 해결 가능 한것 같은데 확인 가능하실까요?

**Comment by morethanmin** [comment]
@yoosion030 해당 이슈 해결해서 배포되었습니다. (#68)

문제없으면 Close 부탁드려요!
