### ISSUE TITLE
author에 사진은 뜨는데 닉네임이 undefinedundefined 로 나옵니다.

### ISSUE THREAD

**Issue by HalamLee** [morethanmin/morethan-log#66]
## **Overview**
<img width="934" alt="image" src="https://user-images.githubusercontent.com/87893624/212467434-c47e3038-e6f6-4a4c-8219-1b11a13a9ec5.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/87893624/212467461-bb657963-248b-49ed-903f-18818c3f1c96.png">

혹시 따로 설정을 해야 하는데 제가 못한 걸까요?
https://www.halamlee.com/refresh-token

**Comment by morethanmin** [comment]
#63 해당 PR에서 말씀해주신 이슈를 수정해서 배포했어요! 
fork되어있는 repo에서 update 해주시면 해결 될 것 같습니다 ㅎㅎ

혹시 해결 되신다면 이 이슈를 close 해주시고, 안되시면 comment 남겨주세요!

**Comment by HalamLee** [comment]
감사합니다! 오픈소스를 활용해본 적이 없어서 업데이트하는 방법을 몰랐었네요! 
말씀해주신 대로 하니 이제 닉네임은 잘 보이는데 사진이 안 보입니다 ㅜㅜ

<img width="940" alt="image" src="https://user-images.githubusercontent.com/87893624/212482847-a711ab07-bba7-40e8-a94d-e3fb077b6832.png">
https://www.halamlee.com/refresh-token

**Comment by morethanmin** [comment]
next.js config 관련 이슈같은데... 확인해보고 수정하겠습니다 감사합니다!

**Comment by morethanmin** [comment]
해당 이슈 수정해서 머지했습니다.  #71 
fork되어있는 repo에서 update 해주시면 해결 될 것 같습니다 ㅎㅎ

**Comment by HalamLee** [comment]
감사합니다!! 방금 확인했는데 잘 보입니다!! 🙇🏻‍♂️
