### ISSUE TITLE
Enabling Discussion for Any feature request.

### ISSUE THREAD

**Issue by kvaishak** [morethanmin/morethan-log#69]
## **Overview**
We can enable discussions for the repository for any Feature request. 
Only Issues that affect the project should be filed under the Issue tab in Github.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/25531121/212627656-e2a759e1-5982-46b4-9624-fb629e7d6f7c.png">

**Comment by morethanmin** [comment]
it's great idea. i opened it!
