### ISSUE TITLE
[Bug]: 콜아웃 안에서 노션에서 제공해주는 커스텀 아이콘으로 설정 시 아이콘이 보이지 않습니다.

### ISSUE THREAD

**Issue by HalamLee** [morethanmin/morethan-log#75]
### Describe the bug

콜아웃 안에서 노션에서 제공해주는 커스텀 아이콘으로 설정 시 아이콘이 보이지 않습니다.

노션에서의 사진과 블로그에서의 사진입니다.

|노션|블로그|
|--|--|
| <img width="569" alt="image" src="https://user-images.githubusercontent.com/87893624/212846985-7a42b269-35df-4307-a602-b6932cf1624b.png">| <img width="758" alt="image" src="https://user-images.githubusercontent.com/87893624/212846883-748b2ac9-975c-4a1e-8a9a-c65a6178051d.png">

확인할 수 있는 페이지 링크입니다!
https://www.halamlee.com/interview-tip-q1

### To reproduce

See error

### Browser

macOS Ventura

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by WhiteHyun** [comment]
저도 이 부분 얼른 해결됐으면 좋겠네요 :'(

**Comment by WhiteHyun** [comment]
이번에 main 브랜치 최신화했더니 해결된 것 같습니다. 근데 issue가 closed되지는 않았네요.

<img width="298" alt="image" src="https://github.com/morethanmin/morethan-log/assets/57972338/431f57ff-e6c2-4951-a52b-a181f8ea383b">

**Comment by morethanmin** [comment]
@HalamLee 문제 없으면 close 하겠습니다 : )
