### ISSUE TITLE
[Bug]: author의 노션 계정에 프로필 사진이 없는 경우 [slug].tsx 페이지 접속시 에러가 발생합니다

### ISSUE THREAD

**Issue by itjustbong** [morethanmin/morethan-log#91]
### Describe the bug

노션 계정의 사진이 없는 경우 하기와 같은 에러가 발생합니다.

<img width="540" alt="스크린샷 2023-01-28 오전 4 56 18" src="https://user-images.githubusercontent.com/29947261/215185258-9dacb182-807e-4e1c-908d-3a04aac31e6b.png">

위 에러는 노션 계정에 프로필 사진을 추가하니, 해결 되었습니다!
<img width="1107" alt="스크린샷 2023-01-28 오전 4 57 12" src="https://user-images.githubusercontent.com/29947261/215185530-e4be1754-8aeb-483f-a2cb-162ed135a337.png">

### To reproduce

위에 관련 내용 작성하였습니다!

### Browser

Google Chrome 109.0.5414.87 (공식 빌드) (arm64)  and MacOS 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by morethanmin** [comment]
이슈 감사합니다! 
이부분은 이미지가 없을 때 예외처리를 해주거나 기본이미지를 보여줘야할 것 같은데, 혹시 의견 있으시면 고려해보고 없으시다면 이미지가 없을 경우에는 닉네임만 표시되는 형태로 수정할게요 👍

**Comment by itjustbong** [comment]
빠른 확인 감사드립니다!

별 것 아닌 에러로 신경쓰실 것 같아,
PR요청했습니다.

노션 프로필 사진이 없을 경우에는 아바타 사진이 출력되도록 수정했습니다!
감사합니다!
