### ISSUE TITLE
[Feature Request] Possible to support cusdis as the comment system?

### ISSUE THREAD

**Issue by 2ndMessiah** [morethanmin/morethan-log#95]
Hey Morethan!!

The blog is basically perfectly all-in-one with such a beautiful and simple design!! Thx for your open source!

My wish is to integrate [Cusdis](https://cusdis.com/) as another choice of the comment system, which doesn't require logging in to leave any comment, whereas the Utterances requires a GitHub account as a necessity.

All the best. Thx.

**Comment by morethanmin** [comment]
hello, @2ndMessiah!

I think Cusdis is very cool comment system, so we can support Cusdis with the comment system.
Can you PR for this feature? If it's hard, I'll update it. 👍 

Thanks for your interest!

**Comment by 2ndMessiah** [comment]
> hello, @2ndMessiah!
> 
> I think Cusdis is very cool comment system, so we can support Cusdis with the comment system. Can you PR for this feature? If it's hard, I'll update it. 👍
> 
> Thanks for your interest!

Thx for the reply! 

But unfortunately I'm not a frontend developer.. Forgive my noobness.  :-(

Nobelium might be useful for a reference: https://github.com/craigary/nobelium, which has integrated [Cusdis](https://github.com/craigary/nobelium/blob/main/blog.config.js).

Appreciate it again.

**Comment by morethanmin** [comment]
Hey @2ndMessiah, now Cusdis is supported by #103! 
If there is no problem, please close the issue 👍

**Comment by 2ndMessiah** [comment]
Hey Morethan!

Gotta salute to your devotion to our blog and say sry for taking up your beautiful weekend time:((

Just built a whole brand new one. Commenting using Cusdis works like a charm, and the approval procedures went on without issues:
![commenting test](https://user-images.githubusercontent.com/22229188/218303092-374e3ba3-165a-4090-8e07-b3125aa0b83f.png)

But there might a minor issue with the background color as you could spot above. I tried some use cases and conclude as below:

1. Cusdis's default dark theme color doesn't fit in with our gray-colored background very well.
2. Cusdis light/dark theme mode would sync with the OS/browser's light/dark settings instead of the "theme" param in site.config.js. 

Some other test drive pic I captured:

1. light theme with dark themed OS
![light theme](https://user-images.githubusercontent.com/22229188/218303562-e14e50de-521e-4cee-9d2b-e5fd2966acf5.png)
2. 
![dark theme with light themed os](https://user-images.githubusercontent.com/22229188/218303662-ddaf393a-3a24-4f8b-8e88-d94e6b740842.png)

Gotta say again I love the aesthetic design of the blog and the color combination...You're such a genius!!
